including builder_example in docs/
gardenlinux/builder pull request #2
Opened 2023-06-17 09:04 UTC by MalteJ

Fixes #1

2023-06-21 11:30 UTC, Vincinator requested changes
We should think about how we distribute the script required to use the builder. 

Copying them from a documentation is not the best idea

2023-06-21 11:30 UTC, Vincinator commented on docs/example/build
We should not copy the files also in `docs/example`, this would introduce duplicates (e.g. `build` and `docs/example/build`). 

Question is: How do I update the build script in gardenlinux/gardenlinux/build with latest changes from gardenlinux/builder/build?

2024-09-05 14:25 UTC, Akendo commented
@MalteJ is this still relevant?

2026-09-15 16:00 UTC, sramapu commented
Closing due to no activity for more than 500d

2026-09-15 16:00 UTC, closed without merging